name: GitHub Pages deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/template/action.yml
    steps:
      - name: Lint code
        run: npm run lint

  # test:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run unit tests
  #       run: |
  #         npm run test
